### ISSUE TITLE
Статус проекта (09.12.2023)

### ISSUE THREAD

**Issue by skordenz** [DrLoon/REDSPb#44]
Задачи на неделю 09.12 - 16.12:
- [x] @TiMeLeSsWorld00 в ближайшее время формирует и отправляет новую версию модели созданную в #36
- [x] @olbenka к 11.12.2023 дорабатывает анализ моделей сегментации #38
- [x] @wenda8 к 11.12.2023 дорабатывает обработку контуров сигналов #37 
- [x] @DrLoon обеспечивает техническую поддержку, Code review #43 и запись демо финального прототипа
- [x] @skordenz прорабатывает отчётность #41 
- [x] Провести созвон с заказчиками с демонстрацией прототипа (13.12)
- [x] Закрыть все задачи к 15.12!
- [x] 15.12 выступление на демо-дне акселератора
